/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_freeaime_systemmediacontrol_service_MediaKey */

#ifndef _Included_be_freeaime_systemmediacontrol_service_MediaKey
#define _Included_be_freeaime_systemmediacontrol_service_MediaKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_freeaime_systemmediacontrol_service_MediaKey
 * Method:    mute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_freeaime_systemmediacontrol_service_MediaKey_mute
  (JNIEnv *, jclass);

/*
 * Class:     be_freeaime_systemmediacontrol_service_MediaKey
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_freeaime_systemmediacontrol_service_MediaKey_play
  (JNIEnv *, jclass);

/*
 * Class:     be_freeaime_systemmediacontrol_service_MediaKey
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_freeaime_systemmediacontrol_service_MediaKey_pause
  (JNIEnv *, jclass);

/*
 * Class:     be_freeaime_systemmediacontrol_service_MediaKey
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_freeaime_systemmediacontrol_service_MediaKey_stop
  (JNIEnv *, jclass);

/*
 * Class:     be_freeaime_systemmediacontrol_service_MediaKey
 * Method:    next
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_freeaime_systemmediacontrol_service_MediaKey_next
  (JNIEnv *, jclass);

/*
 * Class:     be_freeaime_systemmediacontrol_service_MediaKey
 * Method:    previous
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_freeaime_systemmediacontrol_service_MediaKey_previous
  (JNIEnv *, jclass);

/*
 * Class:     be_freeaime_systemmediacontrol_service_MediaKey
 * Method:    lowerVolume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_freeaime_systemmediacontrol_service_MediaKey_lowerVolume
  (JNIEnv *, jclass);

/*
 * Class:     be_freeaime_systemmediacontrol_service_MediaKey
 * Method:    raiseVolume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_freeaime_systemmediacontrol_service_MediaKey_raiseVolume
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
